### ISSUE TITLE
Use a NamedTuple instead of a Dict for simulation results in day 1

### ISSUE THREAD

**Issue by dmbates** [crsl4/julia-workshop#2]
Right now the simulation on Day 1 returns a `Dict` and it would probably be better to return a `NamedTuple`.  (I can rewrite it that way, if you wish.)  A `NamedTuple` is much lighter weight than a `Dict` and a `Vector` of `NamedTuple`s is the archetypal "row table".  Conversely a `NamedTuple` of `Vectors` is the archetypal "column table" which is the lightweight version of a `DataFrame`.

**Comment by dmbates** [comment]
Ah, I just realized that the part about the simulations is probably from the `DrWatson` docs.

**Comment by crsl4** [comment]
yes, I took it from DrWatson's tutorial. Happy to change if you think other strategies are better

**Comment by dmbates** [comment]
Another thing I just noticed is that in section 4 there the loop
```
for (i, d) in enumerate(dicts)
...
```
never uses `i`.

**Comment by crsl4** [comment]
yes! I noticed this as I was teaching. I did not pay attention before when I was shameless copying the code. Something to change!

**Comment by dmbates** [comment]
Depends on the audience but most students in data science should be familiar with data.frame in R or pandas in Python.  The nice thing about the `Tables.jl` package is that you can move back and forth between row-oriented (preferred in the database world) and column-oriented (preferred in the analytics world).  Also I would be inclined to use `Arrow.jl` to save the results instead of BSON.  BSON and JSON are flexible but still have a pretty high overhead.

**Comment by crsl4** [comment]
yes, agreed! I think we can assume the audience will be familiar with data.frame or pandas. I agree with using `Arrow.jl` to save results! (and I did not know that about `Tables.jl`!)

**Comment by dmbates** [comment]
`Tables.jl` is the basis for a lot of the JuliaData approach.  Jacob Quinn, the author of `CSV.jl` and `Arrow.jl` and many other packages is the principal author, which is an advantage (he is very good) and a disadvantage (his documentation is often rather terse).  You have to use it a bit to be able to appreciate the ideas.  The weird thing for a Julia package is that it defines interfaces (a set of method names that must be implemented) rather than types.  The idea is that you can have sources and sinks that behave like row tables or column tables and move the data between them transparently.  Many users don't realize that CSV.File returns a row table and they just wrap the call in `DataFrame` to get a column table.  This idea of the schema allows you to do that.

Do you think we should do a statistics simulation instead of the simulation here?  We could take a very simple linear model, say one subject's data from sleepstudy, and simulate the distribution of the coefficient estimates.  One thing that would show off for Julia is the speed and the ability to run loops without pain.  (I may be getting carried away here.)

**Comment by crsl4** [comment]
I think it is a great idea, yes!! Should we change the order of the sessions then, and begin with `MixedModels` and then the simulation setup with `DrWatson`?

**Comment by crsl4** [comment]
Reiterating, I am happy to throw out what we currently have and re-create everything. Happy to follow your lead!

**Comment by dmbates** [comment]
Let's stay with the general plan of DrWatson for the first hour and MixedModels for the second hour.  I'll see if I can come up with a more statistically relevant simulation for the DrWatson part.

**Comment by crsl4** [comment]
Sounds good, thanks!
